/*
 * This file is generated by jOOQ.
 */
package br.com.upperapps.sakilasparkapi.jooq;


import br.com.upperapps.sakilasparkapi.jooq.tables.Actor;
import br.com.upperapps.sakilasparkapi.jooq.tables.ActorInfo;
import br.com.upperapps.sakilasparkapi.jooq.tables.Address;
import br.com.upperapps.sakilasparkapi.jooq.tables.Category;
import br.com.upperapps.sakilasparkapi.jooq.tables.City;
import br.com.upperapps.sakilasparkapi.jooq.tables.Country;
import br.com.upperapps.sakilasparkapi.jooq.tables.Customer;
import br.com.upperapps.sakilasparkapi.jooq.tables.CustomerList;
import br.com.upperapps.sakilasparkapi.jooq.tables.Film;
import br.com.upperapps.sakilasparkapi.jooq.tables.FilmActor;
import br.com.upperapps.sakilasparkapi.jooq.tables.FilmCategory;
import br.com.upperapps.sakilasparkapi.jooq.tables.FilmList;
import br.com.upperapps.sakilasparkapi.jooq.tables.FilmText;
import br.com.upperapps.sakilasparkapi.jooq.tables.Inventory;
import br.com.upperapps.sakilasparkapi.jooq.tables.Language;
import br.com.upperapps.sakilasparkapi.jooq.tables.NicerButSlowerFilmList;
import br.com.upperapps.sakilasparkapi.jooq.tables.Payment;
import br.com.upperapps.sakilasparkapi.jooq.tables.Rental;
import br.com.upperapps.sakilasparkapi.jooq.tables.SalesByFilmCategory;
import br.com.upperapps.sakilasparkapi.jooq.tables.SalesByStore;
import br.com.upperapps.sakilasparkapi.jooq.tables.Staff;
import br.com.upperapps.sakilasparkapi.jooq.tables.StaffList;
import br.com.upperapps.sakilasparkapi.jooq.tables.Store;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in sakila
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sakila.actor</code>.
     */
    public static final Actor ACTOR = br.com.upperapps.sakilasparkapi.jooq.tables.Actor.ACTOR;

    /**
     * VIEW
     */
    public static final ActorInfo ACTOR_INFO = br.com.upperapps.sakilasparkapi.jooq.tables.ActorInfo.ACTOR_INFO;

    /**
     * The table <code>sakila.address</code>.
     */
    public static final Address ADDRESS = br.com.upperapps.sakilasparkapi.jooq.tables.Address.ADDRESS;

    /**
     * The table <code>sakila.category</code>.
     */
    public static final Category CATEGORY = br.com.upperapps.sakilasparkapi.jooq.tables.Category.CATEGORY;

    /**
     * The table <code>sakila.city</code>.
     */
    public static final City CITY = br.com.upperapps.sakilasparkapi.jooq.tables.City.CITY;

    /**
     * The table <code>sakila.country</code>.
     */
    public static final Country COUNTRY = br.com.upperapps.sakilasparkapi.jooq.tables.Country.COUNTRY;

    /**
     * The table <code>sakila.customer</code>.
     */
    public static final Customer CUSTOMER = br.com.upperapps.sakilasparkapi.jooq.tables.Customer.CUSTOMER;

    /**
     * VIEW
     */
    public static final CustomerList CUSTOMER_LIST = br.com.upperapps.sakilasparkapi.jooq.tables.CustomerList.CUSTOMER_LIST;

    /**
     * The table <code>sakila.film</code>.
     */
    public static final Film FILM = br.com.upperapps.sakilasparkapi.jooq.tables.Film.FILM;

    /**
     * The table <code>sakila.film_actor</code>.
     */
    public static final FilmActor FILM_ACTOR = br.com.upperapps.sakilasparkapi.jooq.tables.FilmActor.FILM_ACTOR;

    /**
     * The table <code>sakila.film_category</code>.
     */
    public static final FilmCategory FILM_CATEGORY = br.com.upperapps.sakilasparkapi.jooq.tables.FilmCategory.FILM_CATEGORY;

    /**
     * VIEW
     */
    public static final FilmList FILM_LIST = br.com.upperapps.sakilasparkapi.jooq.tables.FilmList.FILM_LIST;

    /**
     * The table <code>sakila.film_text</code>.
     */
    public static final FilmText FILM_TEXT = br.com.upperapps.sakilasparkapi.jooq.tables.FilmText.FILM_TEXT;

    /**
     * The table <code>sakila.inventory</code>.
     */
    public static final Inventory INVENTORY = br.com.upperapps.sakilasparkapi.jooq.tables.Inventory.INVENTORY;

    /**
     * The table <code>sakila.language</code>.
     */
    public static final Language LANGUAGE = br.com.upperapps.sakilasparkapi.jooq.tables.Language.LANGUAGE;

    /**
     * VIEW
     */
    public static final NicerButSlowerFilmList NICER_BUT_SLOWER_FILM_LIST = br.com.upperapps.sakilasparkapi.jooq.tables.NicerButSlowerFilmList.NICER_BUT_SLOWER_FILM_LIST;

    /**
     * The table <code>sakila.payment</code>.
     */
    public static final Payment PAYMENT = br.com.upperapps.sakilasparkapi.jooq.tables.Payment.PAYMENT;

    /**
     * The table <code>sakila.rental</code>.
     */
    public static final Rental RENTAL = br.com.upperapps.sakilasparkapi.jooq.tables.Rental.RENTAL;

    /**
     * VIEW
     */
    public static final SalesByFilmCategory SALES_BY_FILM_CATEGORY = br.com.upperapps.sakilasparkapi.jooq.tables.SalesByFilmCategory.SALES_BY_FILM_CATEGORY;

    /**
     * VIEW
     */
    public static final SalesByStore SALES_BY_STORE = br.com.upperapps.sakilasparkapi.jooq.tables.SalesByStore.SALES_BY_STORE;

    /**
     * The table <code>sakila.staff</code>.
     */
    public static final Staff STAFF = br.com.upperapps.sakilasparkapi.jooq.tables.Staff.STAFF;

    /**
     * VIEW
     */
    public static final StaffList STAFF_LIST = br.com.upperapps.sakilasparkapi.jooq.tables.StaffList.STAFF_LIST;

    /**
     * The table <code>sakila.store</code>.
     */
    public static final Store STORE = br.com.upperapps.sakilasparkapi.jooq.tables.Store.STORE;
}
